[workspace]
members = ["crates/cli", "crates/module-parser"]
resolver = "3"

[workspace.package]
version = "0.0.1"
license-file = "LICENSE"
authors = ["CyberFabric"]
repository = "https://github.com/cyberfabric/cf-cli"
description = "Command-line interface for CyberFabric"
edition = "2024"
readme = "README.md"

[workspace.dependencies]
module-parser = { path = "crates/module-parser" }

anyhow = { version = "1.0" }
clap = { version = "4.5", features = ["derive"] }

cargo-generate = { version = "0.23.7" }
cargo_metadata = { version = "0.23.1" }

liquid = { version = "~0.26" } # align with cargo-generate

serde = { version = "1.0", features = ["derive"] }
serde-saphyr = { version = "0.0.19" }
toml = { version = "0.9.8", features = ["serde"] }

notify = { version = "8.2.0", features = ["serde"] }

syn = { version = "2.0.116", features = ["full"] }

[workspace.lints.rust]
unsafe_code = "forbid"
